### ISSUE TITLE
Why do this?

### ISSUE THREAD

**Issue by vitaly-t** [jray/pg-gen#1]
The only place where it makes sense to paginate data is with [pg-query-stream](https://github.com/brianc/node-pg-query-stream).

Paginating query result that's already in memory makes it of little to no value.

**Comment by recursivefunk** [comment]
Hey @vitaly-t sorry just seeing this message. You're right streaming is the best solution for memory conservation. But pg-gen uses a postgresql cursor which, from my understanding, doesn't give you back the entire resultset. Check this out [postgresql cursor](http://www.postgresql.org/docs/9.2/static/plpgsql-cursors.html)

Also, one thing to keep in mind, memory might not necessarily be the problem you're addressing. Streaming assumes you're ready to do something with the data (unless you manually pause/resume etc). This allows you to actively fetch data when you want it. If streams are pushes, this is a pull.

**Comment by vitaly-t** [comment]
I was under impression your library was paging through the data that's already in memory, that's why I asked.

**Comment by recursivefunk** [comment]
Cool. I should probably make that more clear in the readme thanks for asking!

**Comment by vitaly-t** [comment]
N.P. :+1:
